# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kq7v5OsdLv8SIT1edRScu-7-UkflVnaB
"""

import matplotlib.pyplot as plt
import numpy as np

# Step1: データの準備

# 1. 折れ線グラフ用データ
y0 = [1, 2, -5, 2]

# 2. sin関数用データ
x = np.linspace(0, 10, 30)
y1 = np.sin(x)

# 3. ヒストグラム用データ
np.random.seed(0)
y2 = np.random.randn(1000)

# 4. 散布図用データ
np.random.seed(0)
x3 = np.random.rand(50)
y3 = np.random.rand(50)


# Step2: 6個のグラフを表示する領域（2行×3列）を作成
fig, axes = plt.subplots(nrows=2, ncols=3, tight_layout=True)

# Step3: 各領域にグラフを描画する
# (0, 0): 折れ線グラフ
axes[0, 0].plot(y0)
axes[0, 0].set_title("Line Plot")

# (0, 1): sin関数
axes[0, 1].plot(x, y1)
axes[0, 1].set_title("Sin Function")

# (0, 2): ヒストグラム
axes[0, 2].hist(y2)
axes[0, 2].set_title("Histogram")

# (1, 0): 散布図
axes[1, 0].scatter(x3, y3)
axes[1, 0].set_title("Scatter Plot")

# Step4: グラフを表示
plt.show()